apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-server
  name: jupyter-server-svc
  namespace: aihub-portal
spec:
  ports:
  - nodePort: 31584
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-server
  type: NodePort
