kind: PersistentVolume
apiVersion: v1
metadata:
  name: jupyter-pv-volume
  labels:
    type: local
    app: jupyter-server
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/pv/jupyter-pv1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-pv-volume
  labels:
    app: jupyter-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
