apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-server
  labels:
    app: jupyter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-server
  template:
    metadata:
      labels:
        app: jupyter-server
    spec:
      containers:
      - name: jupyter-server
        image: 192.168.0.230:30002/jupyter-test:v3
        ports:
          - containerPort: 8888
        volumeMounts:
          - name: storage-volume
            mountPath: /home/woori
      volumes: 
        - name: storage-volume 
          persistentVolumeClaim:
            claimName: jupyter-pv-volume
