apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-pv-volume
  labels:
    type: local
spec:
  storageClassName: localvolumeprovisioner
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/jupyter-pv1"
      
      
   
