apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: 5wjdgns21/jupyter
        image: 192.168.0.230:30002/5wjdgns21/jupyter-test:v3
        ports:
          - containerPort: 8888
        volumeMounts:
          - name: storage-volume
            mountPath: /home/woori
      volumes: 
        - name: storage-volume 
          emptyDir: {} 
