apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-app
  name: jupyter-app-svc
  namespace: aihub-portal
spec:
  ports:
  - nodePort: 31584
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-app
  type: NodePort
